### ISSUE TITLE
Base64 encoded relicts inside tokendata

### ISSUE THREAD

**Issue by yoshimo** [nohajc/netflix-mitm-proxy#1] opened 2019-11-08 21:38 UTC
Is the plugin supposed to decode all base64 strings into ascii if possible?
Sometimes things like

```
    "useridtoken": {
        "tokendata": "eyJ1c2VyZGF0YSI6IkJRQ0FBQUVCRURPRDZBTWRIWWRTMDN5VmRjM0NjMVNCQUNLaTNPRnVBbVVSMVZ6S3RtMldOS3JDOEpYNUNjMW56MVYxUEhxaWFLL09WTFg1NFIwNEE2Q3c0dlZNdzhsWjFycUtRZDR2NHg0MVM3YXdBWEkyL2JaWEVoQkNLdFN3akoyOFRBUlViMmo5MnlNbzM5djh0VjR6YmFYS2VNT3A4aml6MzJqTjV2N0JqZVF6QlY1WXFES05YdXNIVnNuWVFaVmRocWdrb1pYdmI1YzVOZ3IrbXpPQ01keVZiMmZxMHhVVER6WmV0OWVNQ0FGclNhUWRHYVJLdEkxSHdqUzJPNStFRVhNUi9XeGlGQTBpendVZGd6aFVMU2R2Y29ON3dYQVp5Z1QzSUt1MUk0cXoyc2FPOHVWL05jS3NaRTh1enF0NWJmQTBmT2VJVTdDanhhdXZ1cVRaUmxqdUlCR1hqM0t6VFlrRHJXdzNhV2J0WFVlbGhZcz0iLCJtdHNlcmlhbG51bWJlciI6Mzc1MTg2NTU1MzE5NDA1NiwicmVuZXdhbHdpbmRvdyI6MTU3MzI3NTk2OSwic2VyaWFsbnVtYmVyIjo4MjcwMTg3Mzk4MDY2MjYwLCJleHBpcmF0aW9uIjoxNTc0NDU2NzY5fQ==",
        "signature": "AQEAgQABASDBAlTf3ijd3CvhpR/Jg2irVpQbtGGNQ2pl2wTy3XD57Xq+tPM="
    },
```

can be further decoded into 

```
"tokendata": "{"
userdata ":"
BQCAAAEBEDOD6AMdHYdS03yVdc3Cc1SBACKi3OFuAmUR1VzKtm2WNKrC8JX5Cc1nz1V1PHqiaK / OVLX54R04A6Cw4vVMw8lZ1rqKQd4v4x41S7awAXI2 / bZXEhBCKtSwjJ28TARUb2j92yMo39v8tV4zbaXKeMOp8jiz32jN5v7BjeQzBV5YqDKNXusHVsnYQZVdhqgkoZXvb5c5Ngr + mzOCMdyVb2fq0xUTDzZet9eMCAFrSaQdGaRKtI1HwjS2O5 + EEXMR / WxiFA0izwUdgzhULSdvcoN7wXAZygT3IKu1I4qz2saO8uV / NcKsZE8uzqt5bfA0fOeIU7CjxauvuqTZRljuIBGXj3KzTYkDrWw3aWbtXUelhYs = ","
mtserialnumber ":3751865553194056,"
renewalwindow ":1573275969,"
serialnumber ":8270187398066260,"
expiration ":1574456769}",
```

**Comment by nohajc** [comment] 2019-11-09 00:43
I only focused on base64 containing encrypted and/or compressed payload.
The sole purpose of the script is to decrypt MSL so you can see how the decrypted traffic looks like.

I could do what you suggest but it should also be evident from the dump what the raw request/response is, so you know exactly what to assemble when re-implementing the API.

**Comment by yoshimo** [comment] 2019-11-09 04:56
replicating the original is what we are after, but indeed a mode that  helps to understand the data with complete decoding and nice formatting would certainly help.
How would i know what we forgot to implement when i just see encoded parts?

**Comment by nohajc** [comment] 2019-11-09 11:14
I agree.

**Comment by nohajc** [comment] 2019-12-08 11:08
Closing as duplicate of #2

**Closed as completed by nohajc** 2019-12-08 11:08 UTC
Labels: duplicate
